# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckFF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Fullfilments Check',
                'verbose_name_plural': 'Fulfillments Checks',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idCourse', models.AutoField(primary_key=True, serialize=False)),
                ('yearCourse', models.IntegerField()),
                ('courseType', models.CharField(choices=[('1', '1\xba a\xf1o'), ('2', '2\xba a\xf1o'), ('3', '3\xba a\xf1o')], max_length=128)),
                ('courseDivision', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=128)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('nameFF', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Fulfillment',
                'verbose_name_plural': 'Fulfillments',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('nameProject', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectStages',
            fields=[
                ('namePS', models.CharField(max_length=128)),
                ('calification', models.IntegerField()),
                ('classes', models.IntegerField()),
                ('idPS', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Project Stage',
                'verbose_name_plural': 'Project Stages',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('namePupil', models.CharField(max_length=128)),
                ('surnamePupil', models.CharField(max_length=128)),
                ('idPupil', models.AutoField(primary_key=True, serialize=False)),
                ('idCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Course')),
            ],
            options={
                'verbose_name': 'Pupil',
                'verbose_name_plural': 'Pupils',
            },
        ),
        migrations.CreateModel(
            name='PupilFollowing',
            fields=[
                ('idPF', models.AutoField(primary_key=True, serialize=False)),
                ('presencePF', models.BooleanField()),
                ('datePF', models.DateField()),
                ('commentPF', models.TextField(blank=True)),
                ('idPupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Pupil')),
            ],
            options={
                'verbose_name': 'Pupil Following',
                'verbose_name_plural': 'Pupils Following',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('idSubject', models.AutoField(primary_key=True, serialize=False)),
                ('nameSubject', models.CharField(max_length=128)),
                ('idCourse', models.ManyToManyField(blank=True, to='database.Course')),
                ('nameFF', models.ManyToManyField(blank=True, to='database.Fulfillment')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.AddField(
            model_name='pupilfollowing',
            name='idSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Subject'),
        ),
        migrations.AddField(
            model_name='projectstages',
            name='idPupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Pupil'),
        ),
        migrations.AddField(
            model_name='projectstages',
            name='nameProject',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='database.Projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='idSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Subject'),
        ),
        migrations.AddField(
            model_name='checkff',
            name='idPF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PupilFollowing'),
        ),
        migrations.AddField(
            model_name='checkff',
            name='nameFF',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='database.Fulfillment'),
        ),
    ]
