# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('nameActivity', models.CharField(max_length=128)),
                ('idActivity', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idCourse', models.AutoField(primary_key=True, serialize=False)),
                ('cycle', models.IntegerField()),
                ('courseType', models.CharField(choices=[('1', '1\xba a\xf1o'), ('2', '2\xba a\xf1o'), ('3', '3\xba a\xf1o')], max_length=128)),
                ('courseDivision', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=128)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='dailyFulfillment',
            fields=[
                ('idDF', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Cumplimiento diario',
                'verbose_name_plural': 'Cumplimientos diarios',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('idDocument', models.AutoField(primary_key=True, serialize=False)),
                ('nameDocument', models.CharField(max_length=128)),
                ('visible', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('nameFF', models.CharField(max_length=128)),
                ('idFF', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Cumplimiento',
                'verbose_name_plural': 'Cumplimientos',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('idModule', models.AutoField(primary_key=True, serialize=False)),
                ('nameModule', models.CharField(max_length=128)),
                ('idCourse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.Course')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='OnClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Activity')),
            ],
            options={
                'verbose_name': 'Trabajo en Clase',
                'verbose_name_plural': 'Trabajos en Clase',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('nameProject', models.CharField(max_length=128)),
                ('idProject', models.AutoField(primary_key=True, serialize=False)),
                ('idModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Module')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('nameRotation', models.CharField(max_length=32)),
                ('idRotation', models.AutoField(primary_key=True, serialize=False)),
                ('idCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Course')),
                ('idModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Module')),
            ],
            options={
                'verbose_name': 'Rotacion',
                'verbose_name_plural': 'Rotaciones',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('numberOfRegistration', models.IntegerField()),
                ('idCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Course')),
                ('idRotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Rotation')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='StudentFollowing',
            fields=[
                ('idSF', models.AutoField(primary_key=True, serialize=False)),
                ('presenceSF', models.BooleanField()),
                ('dateSF', models.DateField()),
                ('commentPF', models.TextField(blank=True)),
                ('idModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Module')),
                ('idStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Student')),
            ],
            options={
                'verbose_name': 'Seguimiento de Alumno',
                'verbose_name_plural': 'Seguimientos de Alumno',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('boss', models.BooleanField()),
                ('password', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfClasses', models.IntegerField()),
                ('calification', models.IntegerField()),
                ('hasFinish', models.BooleanField()),
                ('idActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Activity')),
                ('idStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Student')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.AddField(
            model_name='studentfollowing',
            name='idTeacher',
            field=models.ManyToManyField(to='database.Teacher'),
        ),
        migrations.AddField(
            model_name='project',
            name='idTeacher',
            field=models.ManyToManyField(to='database.Teacher'),
        ),
        migrations.AddField(
            model_name='onclass',
            name='idSF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.StudentFollowing'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='idProject',
            field=models.ManyToManyField(blank=True, to='database.Project'),
        ),
        migrations.AddField(
            model_name='document',
            name='idModule',
            field=models.ManyToManyField(blank=True, to='database.Module'),
        ),
        migrations.AddField(
            model_name='dailyfulfillment',
            name='idFF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Fulfillment'),
        ),
        migrations.AddField(
            model_name='dailyfulfillment',
            name='idSF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.StudentFollowing'),
        ),
        migrations.AddField(
            model_name='activity',
            name='idProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Project'),
        ),
    ]
