# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyFulfillment',
            fields=[
                ('idDF', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField()),
                ('idFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Fulfillment')),
                ('idSF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.StudentFollowing')),
            ],
            options={
                'verbose_name': 'Cumplimiento diario',
                'verbose_name_plural': 'Cumplimientos diarios',
            },
        ),
    ]
