# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='visible',
        ),
        migrations.AddField(
            model_name='document',
            name='archivo',
            field=models.FileField(blank=True, upload_to='documentos', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='document',
            name='commentDoc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='idCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Course'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='idModule',
        ),
        migrations.AddField(
            model_name='document',
            name='idModule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Module'),
        ),
        migrations.AlterField(
            model_name='document',
            name='nameDocument',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
