# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-28 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentFollowing',
            new_name='StudentFollowingModel',
        ),
    ]
