# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20161128_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onclass',
            name='idActivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Activity'),
        ),
    ]
