# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20161128_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='classFulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField()),
                ('idFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Fulfillment')),
                ('idSF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.StudentFollowingModel')),
            ],
            options={
                'verbose_name': 'Cumplimiento en clase',
                'verbose_name_plural': 'Cumplimientos en clase',
            },
        ),
    ]
