# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rotation_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentfollowing',
            name='exists',
            field=models.BooleanField(default=True),
        ),
    ]
