# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-28 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_classfulfillment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working',
            name='calification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
