# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20161128_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='onclass',
            name='rotationLog',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
