# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherRegister', '0003_auto_20160623_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesores',
            options={'permissions': (('Deshabilitado', 'El profesor no puede ingresar al sistema aun'), ('Habilitado', 'El profesor puede ingresar al sistema y modificar datos'))},
        ),
        migrations.AlterField(
            model_name='profesores',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
