# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idCourse', models.AutoField(primary_key=True, serialize=False)),
                ('yearCourse', models.IntegerField()),
                ('divisionCourse', models.CharField(choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C')], max_length=128)),
                ('divisionYear', models.CharField(choices=[('1', '1er A\xf1o'), ('2', '2do A\xf1o'), ('3', '3er A\xf1o')], max_length=128)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('namePupil', models.CharField(max_length=128)),
                ('surnamePupil', models.CharField(max_length=128)),
                ('idPupil', models.AutoField(primary_key=True, serialize=False)),
                ('idCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Course')),
            ],
            options={
                'verbose_name': 'Pupil',
                'verbose_name_plural': 'Pupils',
            },
        ),
        migrations.CreateModel(
            name='PupilFollowing',
            fields=[
                ('idPF', models.AutoField(primary_key=True, serialize=False)),
                ('presencePF', models.BooleanField()),
                ('datePF', models.DateField()),
                ('commentPF', models.TextField()),
                ('idPupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Pupil')),
            ],
            options={
                'verbose_name': 'Pupil Following',
                'verbose_name_plural': 'Pupils Following',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('idSubject', models.AutoField(primary_key=True, serialize=False)),
                ('nameSubject', models.CharField(max_length=128)),
                ('idCourse', models.ManyToManyField(to='page.Course')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.AddField(
            model_name='pupilfollowing',
            name='idSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Subject'),
        ),
    ]
