# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('idFF', models.AutoField(primary_key=True, serialize=False)),
                ('nameFF', models.CharField(max_length=128)),
                ('checkFF', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Fulfillment',
                'verbose_name_plural': 'Fulfillments',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='idFF',
            field=models.ManyToManyField(to='page.Fulfillment'),
        ),
    ]
