# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20160616_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillment',
            name='checkFF',
        ),
    ]
