# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20160616_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('nameProject', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('idSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Subject')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectStages',
            fields=[
                ('namePS', models.CharField(max_length=128)),
                ('idPS', models.AutoField(primary_key=True, serialize=False)),
                ('idProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Projects')),
            ],
            options={
                'verbose_name': 'Project Stage',
                'verbose_name_plural': 'Project Stages',
            },
        ),
    ]
