# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_projects_projectstages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupilfollowing',
            name='commentPF',
            field=models.TextField(blank=True),
        ),
    ]
