# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20160616_1602'),
        ('page', '0008_auto_20160616_1531'),
    ]

    operations = [
    ]
