# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20160623_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDivision',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='courseType',
            field=models.CharField(choices=[('1', '1\xba a\xf1o'), ('2', '2\xba a\xf1o'), ('3', '3\xba a\xf1o')], max_length=128),
        ),
    ]
