# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20160623_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='idCourse',
            field=models.ManyToManyField(blank=True, to='page.Course'),
        ),
    ]
