# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20160623_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Fulfillments Table',
                'verbose_name_plural': 'Fulfillments Tables',
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='idFF',
        ),
        migrations.AddField(
            model_name='fulfillmentstable',
            name='idSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Subject'),
        ),
        migrations.AddField(
            model_name='fulfillmentstable',
            name='nameFF',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='page.Fulfillment'),
        ),
    ]
