# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20160627_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckFF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.PupilFollowing')),
                ('nameFF', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='page.Fulfillment')),
            ],
            options={
                'verbose_name': 'Fullfilments Check',
                'verbose_name_plural': 'Fulfillments Checks',
            },
        ),
        migrations.RemoveField(
            model_name='fulfillmentstable',
            name='idSubject',
        ),
        migrations.RemoveField(
            model_name='fulfillmentstable',
            name='nameFF',
        ),
        migrations.AddField(
            model_name='subject',
            name='nameFF',
            field=models.ManyToManyField(to='page.Fulfillment'),
        ),
        migrations.DeleteModel(
            name='FulfillmentsTable',
        ),
    ]
