# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_auto_20160627_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkff',
            name='check',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
