# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_checkff_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstages',
            name='calification',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projectstages',
            name='classes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
