# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_auto_20160628_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstages',
            old_name='idProject',
            new_name='nameProject',
        ),
    ]
