# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20160629_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstages',
            name='nameProject',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='page.Projects'),
        ),
    ]
