# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20160629_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='nameFF',
            field=models.ManyToManyField(blank=True, to='page.Fulfillment'),
        ),
    ]
