# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_auto_20160804_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calification',
            fields=[
                ('note', models.IntegerField()),
                ('classes', models.IntegerField()),
                ('idCal', models.AutoField(primary_key=True, serialize=False)),
                ('idPS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.ProjectStages')),
                ('idPupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Pupil')),
                ('nameProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Projects')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
            },
        ),
    ]
