# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_calification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calification',
            name='idPS',
        ),
        migrations.RemoveField(
            model_name='calification',
            name='idPupil',
        ),
        migrations.RemoveField(
            model_name='calification',
            name='nameProject',
        ),
        migrations.AddField(
            model_name='projectstages',
            name='classes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectstages',
            name='idPupil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page.Pupil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectstages',
            name='note',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Calification',
        ),
    ]
