# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_auto_20160804_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstages',
            old_name='note',
            new_name='calification',
        ),
    ]
